<?xml version="1.0" encoding="utf-8"?>

<Project>
    <PropertyGroup>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <PublishAot>false</PublishAot>
        <SatelliteResourceLanguages>pt-BR</SatelliteResourceLanguages>
        <NoWarn>
            $(NoWarn)
        </NoWarn>
        <NoError>
            $(NoError);
        </NoError>
    </PropertyGroup>
</Project>
